<a href="https://colab.research.google.com/github/Anikrai11/titanic/blob/main/Ecomerce_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np
import pandas as pd

In [43]:
df=pd.read_csv("/content/new module aa.csv")

In [44]:
df

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
0,Dr.,Ray,Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5.020000e+15,18-May,Solo,8.36,Blue,126.23.139.2,Sunday,pm,4/5/1930
1,Miss,Claudia,Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5.020000e+15,28-Jul,Visa,68.31,Black,106.198.76.211,Tuesday,am,12/20/1926
2,Miss,Harry,Meyer,zuz@lo.wf,Female,51,CSX Corp.,Political Scientist,(539) 246-1806,A0Z 6P9,NS,6.300000e+15,23-Feb,Switch,34.65,Black,186.150.187.29,Wednesday,pm,8/20/1931
3,Miss,Edith,Gilbert,hansohsi@jupec.md,Female,55,Murphy Oil Corporation,Transportation Manager,(984) 962-7494,P9I 9H3,YT,3.530000e+15,28-Feb,Maestro,64.59,White,80.140.57.161,Saturday,am,6/18/2001
4,Dr.,Lura,Murphy,webediti@je.st,Female,20,PETsMART Inc,Statistician,(902) 568-9748,S1A 6K0,ON,4.030000e+15,25-Oct,Diners Club International,20.83,Yellow,211.103.43.41,Friday,pm,6/14/2045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,Mr.,John,Maxwell,larlisu@sejenu.ad,Female,38,Spherion Corp,Publishing Director,(873) 298-1178,V4U 0X2,YT,6.330000e+15,28-Apr,Visa Electron,90.37,Red,194.14.119.109,Sunday,am,4/18/2014
29996,Dr.,Alfred,Bass,le@duridzo.gh,Female,24,Ford Motor Co,Diamond Merchant,(541) 904-3323,T9O 1H6,PE,2.010000e+14,26-Dec,American Express,5.94,White,154.114.74.254,Sunday,pm,9/27/2068
29997,Mrs.,Edward,Curtis,ta@kucemah.et,Female,56,Park Place Entertainment Corp,Executive Director,(375) 931-8605,X5Z 4E1,QC,2.010000e+14,21-Jun,Maestro,65.66,Black,188.0.106.220,Monday,pm,9/7/1997
29998,Mr.,Max,Woods,li@mincoz.mp,Female,64,Nacco Industries Inc,University Administrator,(786) 481-9627,G0S 9Q8,NS,3.000000e+13,23-Aug,Solo,52.66,Black,129.168.247.27,Monday,pm,9/8/1938
29999,Mr.,Olga,Rodriguez,ner@ota.ec,Male,22,Texas Industries Inc.,Leasing Manager,(841) 962-4087,N2D 5K3,BC,6.300000e+15,24-May,InstaPayment,17.71,Yellow,70.2.107.65,Wednesday,am,6/22/1956

In [45]:
df.head()

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
0,Dr.,Ray,Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5.020000e+15,18-May,Solo,8.36,Blue,126.23.139.2,Sunday,pm,4/5/1930
1,Miss,Claudia,Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5.020000e+15,28-Jul,Visa,68.31,Black,106.198.76.211,Tuesday,am,12/20/1926
2,Miss,Harry,Meyer,zuz@lo.wf,Female,51,CSX Corp.,Political Scientist,(539) 246-1806,A0Z 6P9,NS,6.300000e+15,23-Feb,Switch,34.65,Black,186.150.187.29,Wednesday,pm,8/20/1931
3,Miss,Edith,Gilbert,hansohsi@jupec.md,Female,55,Murphy Oil Corporation,Transportation Manager,(984) 962-7494,P9I 9H3,YT,3.530000e+15,28-Feb,Maestro,64.59,White,80.140.57.161,Saturday,am,6/18/2001
4,Dr.,Lura,Murphy,webediti@je.st,Female,20,PETsMART Inc,Statistician,(902) 568-9748,S1A 6K0,ON,4.030000e+15,25-Oct,Diners Club International,20.83,Yellow,211.103.43.41,Friday,pm,6/14/2045

In [46]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   prefix      30000 non-null  object
 1   first       30000 non-null  object
 2   last        30000 non-null  object
 3   email       30000 non-null  object
 4   gender      30000 non-null  object
 5   age         30000 non-null  int64
 6   company     30000 non-null  object
 7   profession  30000 non-null  object
 8   phone       30000 non-null  object
 9   postal      30000 non-null  object
 10  province    30000 non-null  object
 11  cc_no       30000 non-null  float64
 12  cc_exp      30000 non-null  object
 13  cc_type     30000 non-null  object
 14  price(CAD)  30000 non-null  float64
 15  fav_color   30000 non-null  object
 16  ip          30000 non-null  object
 17  weekday     30000 non-null  object
 18  ampm        30000 non-null  object
 19  date        30000 non-null  object
dtypes: float64(2), int64(1), object(17)
memory usage: 4.6+ MB

# 4

In [47]:

print(df["age"].min())
print(df["age"].max())
print(df["age"].mean())

18
65
41.550066666666666

# 5

In [48]:
df["first"].value_counts().head(3)

first
Willie     130
Francis    124
Eula        86
Name: count, dtype: int64

In [49]:
df.columns

Index(['prefix', 'first', 'last', 'email', 'gender', 'age', 'company',
       'profession', 'phone', 'postal', 'province', 'cc_no', 'cc_exp',
       'cc_type', 'price(CAD)', 'fav_color', 'ip', 'weekday', 'ampm', 'date'],
      dtype='object')

# 6

In [50]:
phone_count=(df["phone"].value_counts())
dupliactes=phone_count[phone_count==2]
print(dupliactes)
phone_number=dupliactes.index[0]
print(df[df["phone"]==phone_number][["first","last","email","phone"]])

phone
(263) 382-8004    2
Name: count, dtype: int64
    first   last                email           phone
15  Lilly  Tyler      kofadu@itohi.tf  (263) 382-8004
16  Peter   Cain  megkosig@anazeor.gn  (263) 382-8004

# 7

In [51]:
print((df['profession']=="Structural Engineer").sum())

87

In [52]:
df.columns

Index(['prefix', 'first', 'last', 'email', 'gender', 'age', 'company',
       'profession', 'phone', 'postal', 'province', 'cc_no', 'cc_exp',
       'cc_type', 'price(CAD)', 'fav_color', 'ip', 'weekday', 'ampm', 'date'],
      dtype='object')

# 8

In [53]:
result=df[(df['profession']=="Structural Engineer")&(df["gender"]=="Male")]
print(len(result))

43

# 9

In [54]:
reasult=df[(df["profession"]=="Structural Engineer")&(df["gender"]=="Female")&(df["province"]=="AB")]

In [55]:
print(reasult[["first","last","gender","profession","province"]])

      first      last  gender           profession province
8858    Roy   Stanley  Female  Structural Engineer       AB
9058   Lora   Kennedy  Female  Structural Engineer       AB
24736  Nell  Richards  Female  Structural Engineer       AB
29865   Don  McDaniel  Female  Structural Engineer       AB

In [57]:
df.columns

Index(['prefix', 'first', 'last', 'email', 'gender', 'age', 'company',
       'profession', 'phone', 'postal', 'province', 'cc_no', 'cc_exp',
       'cc_type', 'price(CAD)', 'fav_color', 'ip', 'weekday', 'ampm', 'date'],
      dtype='object')

# 10

In [58]:
print(df["price(CAD)"].max())
print(df["price(CAD)"].min())
print(df["price(CAD)"].mean())

100.0
0.0
49.990775

# 11

In [59]:
cast=df[df["price(CAD)"]==0]
print(cast[["first","last","email","price(CAD)"]])

       first   last           email  price(CAD)
5320   Bruce  Bryan  ru@pubuspuh.cl         0.0
10597  Flora  Clark      wad@me.com         0.0

# New Section

# 12

In [60]:
cast=df[df["price(CAD)"]>=100]
print(len(cast))
print(cast[["first","last","email","price(CAD)"]])

3
         first         last          email  price(CAD)
76     Gregory        Brown     hav@jek.gs       100.0
21093     Cody  Christensen    get@jovu.ag       100.0
24385   Lizzie        Dixon  goh@tuwjaz.gd       100.0

In [61]:
df.columns

Index(['prefix', 'first', 'last', 'email', 'gender', 'age', 'company',
       'profession', 'phone', 'postal', 'province', 'cc_no', 'cc_exp',
       'cc_type', 'price(CAD)', 'fav_color', 'ip', 'weekday', 'ampm', 'date'],
      dtype='object')

In [62]:
df["cc_no"]

0        5.020000e+15
1        5.020000e+15
2        6.300000e+15
3        3.530000e+15
4        4.030000e+15
             ...
29995    6.330000e+15
29996    2.010000e+14
29997    2.010000e+14
29998    3.000000e+13
29999    6.300000e+15
Name: cc_no, Length: 30000, dtype: float64

## problem face this question

# 13 number is very defficult

In [77]:
df["cc_no"]

0        5.020000e+15
1        5.020000e+15
2        6.300000e+15
3        3.530000e+15
4        4.030000e+15
             ...
29995    6.330000e+15
29996    2.010000e+14
29997    2.010000e+14
29998    3.000000e+13
29999    6.300000e+15
Name: cc_no, Length: 30000, dtype: float64

In [79]:
ttt=df[df["cc_no"]==5020000000000230]
print(len(ttt))

0

In [65]:
df["cc_exp"]

0        18-May
1        28-Jul
2        23-Feb
3        28-Feb
4        25-Oct
          ...
29995    28-Apr
29996    26-Dec
29997    21-Jun
29998    23-Aug
29999    24-May
Name: cc_exp, Length: 30000, dtype: object

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   prefix      30000 non-null  object
 1   first       30000 non-null  object
 2   last        30000 non-null  object
 3   email       30000 non-null  object
 4   gender      30000 non-null  object
 5   age         30000 non-null  int64
 6   company     30000 non-null  object
 7   profession  30000 non-null  object
 8   phone       30000 non-null  object
 9   postal      30000 non-null  object
 10  province    30000 non-null  object
 11  cc_no       30000 non-null  float64
 12  cc_exp      30000 non-null  object
 13  cc_type     30000 non-null  object
 14  price(CAD)  30000 non-null  float64
 15  fav_color   30000 non-null  object
 16  ip          30000 non-null  object
 17  weekday     30000 non-null  object
 18  ampm        30000 non-null  object
 19  date        30000 non-null  object
dtypes: float64(2), int64(1), object(17)
memory usage: 4.6+ MB

# 14

In [72]:
f=pd.to_datetime(df["cc_exp"],format="%y-%b")

In [75]:
cards_2019=df[f.dt.year==2019]
print(len(cards_2019))

2684

In [129]:
e=df[df["cc_type"]=="Visa"].value_counts()
e

prefix  first      last       email                 gender  age  company                       profession                          phone           postal   province  cc_no         cc_exp  cc_type  price(CAD)  fav_color  ip               weekday    ampm  date
Mrs.    Zachary    Flores     vovuh@zeli.uy         Male    62   Lowe's Companies Inc.         Membership Chairman                 (777) 396-1076  V6R 4X4  ON        6.330000e+15  28-Feb  Visa     59.09       Yellow     25.125.152.53    Saturday   am    10/2/2006     1
Dr.     Adam       Brooks     jasun@gmail.com       Male    42   Payless Shoesource Inc        Organizational Development Manager  (947) 945-1387  C5G 3P4  NS        4.760000e+15  22-Jun  Visa     38.10       White      245.1.199.5      Thursday   pm    12/18/2035    1
                   Rice       zu@ra.ua              Male    34   Cadence Design Systems, Inc.  City Manager                        (554) 881-6071  A3T 5O7  NS        3.000000e+13  26-Nov  Visa     18.22       Yellow     100.218.90.218   Saturday   pm    4/22/2049     1
        Adele      Martinez   deh@hotmail.com       Male    40   Pro-Fac Cooperative Inc.      Executive Director                  (721) 539-6779  R2A 6D2  NL        6.010000e+15  18-Sep  Visa     23.54       White      150.235.190.193  Tuesday    pm    8/1/2044      1
        Adrian     Anderson   tehot@outlook.com     Female  33   Dover Corporation, Inc.       Underwriter                         (277) 616-8688  J5Z 4D4  YT        4.760000e+15  27-Oct  Visa     18.39       Black      194.132.112.188  Wednesday  am    4/27/2063     1
                                                                                                                                                                                                                                                                           ..
        Alfred     Norton     ufuteosa@veheckok.eh  Male    39   Energy East Corporation       Transportation Manager              (572) 648-4921  P5S 6Q5  NT        5.110000e+15  21-Dec  Visa     19.69       Red        118.123.215.109  Wednesday  am    3/15/2053     1
                   McCormick  cisof@sac.fo          Female  31   Tyson Foods Inc               Stockbroker                         (556) 277-3288  J0I 9L4  NS        6.260000e+15  18-Dec  Visa     98.69       Red        83.94.109.230    Saturday   pm    7/9/2063      1
        Alex       Guerrero   ba@jujenwi.mr         Female  58   Ashland Inc.                  Scientific Programmer               (324) 284-6072  A6F 1G0  MB        4.100000e+15  28-Nov  Visa     82.34       Blue       147.243.233.135  Monday     pm    10/24/1990    1
                   Adkins     okfa@outlook.com      Male    45   Office Depot Inc.             Physician Assistant                 (809) 254-2377  K2M 7A9  BC        5.480000e+15  22-Aug  Visa     20.24       White      215.209.30.206   Friday     pm    8/7/1956      1
        Alejandro  Parker     ubleruk@me.com        Male    48   Marsh Supermarkets Inc.       Communications Affairs Director     (729) 898-9705  P6U 0G0  BC        6.300000e+15  21-Apr  Visa     37.27       White      120.43.102.11    Thursday   am    9/21/2067     1
Name: count, Length: 1721, dtype: int64

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   prefix      30000 non-null  object
 1   first       30000 non-null  object
 2   last        30000 non-null  object
 3   email       30000 non-null  object
 4   gender      30000 non-null  object
 5   age         30000 non-null  int64
 6   company     30000 non-null  object
 7   profession  30000 non-null  object
 8   phone       30000 non-null  object
 9   postal      30000 non-null  object
 10  province    30000 non-null  object
 11  cc_no       30000 non-null  float64
 12  cc_exp      30000 non-null  object
 13  cc_type     30000 non-null  object
 14  price(CAD)  30000 non-null  float64
 15  fav_color   30000 non-null  object
 16  ip          30000 non-null  object
 17  weekday     30000 non-null  object
 18  ampm        30000 non-null  object
 19  date        30000 non-null  object
dtypes: float64(2), int64(1), object(17)
memory usage: 4.6+ MB

# 15

In [101]:
print((df["cc_type"]=="Visa").sum())

1721

In [104]:
df["price(CAD)"]

0         8.36
1        68.31
2        34.65
3        64.59
4        20.83
         ...
29995    90.37
29996     5.94
29997    65.66
29998    52.66
29999    17.71
Name: price(CAD), Length: 30000, dtype: float64

# 16

In [109]:
result=df[(df["price(CAD)"]==100)&(df["cc_type"]=="Visa")]

In [114]:
r=(result[["first","last","cc_type","price(CAD)"]])
r

      first   last cc_type  price(CAD)
76  Gregory  Brown    Visa       100.0

#17

In [115]:
df["profession"].value_counts().head(2)

profession
Preschool Teacher       112
Distribution Manager    107
Name: count, dtype: int64

# 18

In [119]:
providers=df["email"].str.split("@").str[1]
p=(providers.value_counts().head(5))
p

email
gmail.com      1687
me.com         1676
outlook.com    1664
live.com       1660
hotmail.com    1659
Name: count, dtype: int64

# 19

In [126]:
edu=(df["email"].str.split("@").str[1]=="am.edu")
e=edu.sum()
e

np.int64(1)

# 20

In [121]:
w=df["weekday"].value_counts()
w

weekday
Saturday     4376
Wednesday    4365
Thursday     4327
Friday       4316
Monday       4216
Sunday       4213
Tuesday      4187
Name: count, dtype: int64